INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
INSERT INTO organization (name, address, city, state, zip, phone_number, website, food, health_care, daily_care, shelter) VALUES 
